<?php

$http_status_codes = [

    // Informational 1xx
    ['code' => 100, 'phrase' => 'ℹ️ Continue',
        'description' => 'The server has received the request headers and the client should proceed to send the request body.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-100-continue',
        'spec_title' => 'RFC9110 - 100 Continue'],
    ['code' => 101, 'phrase' => '🔄 Switching Protocols',
        'description' => 'The server is switching protocols as requested by the client.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-101-switching-protocols',
        'spec_title' => 'RFC9110 - 101 Switching Protocols'],
    ['code' => 102, 'phrase' => '⏳ Processing',
        'description' => 'The server has received and is processing the request, but no response is available yet.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-102-processing',
        'spec_title' => 'RFC9110 - 102 Processing'],
    ['code' => 103, 'phrase' => '🔜 Early Hints',
        'description' => 'The server is likely to send a final response after the request has been fully received.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-103-early-hints',
        'spec_title' => 'RFC9110 - 103 Early Hints'],

    // Success 2xx
    ['code' => 200, 'phrase' => '✅ OK',
        'description' => 'The request has succeeded.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-200-ok',
        'spec_title' => 'RFC9110 - 200 OK'],
    ['code' => 201, 'phrase' => '🆕 Created',
        'description' => 'The request has been fulfilled and a new resource has been created.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-201-created',
        'spec_title' => 'RFC9110 - 201 Created'],
    ['code' => 202, 'phrase' => '🔄 Accepted',
        'description' => 'The request has been accepted for processing, but the processing has not been completed.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-202-accepted',
        'spec_title' => 'RFC9110 - 202 Accepted'],
    ['code' => 203, 'phrase' => 'ℹ️ Non-Authoritative Information',
        'description' => 'The request was successful, but the response is from a third party.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-203-non-authoritative-information',
        'spec_title' => 'RFC9110 - 203 Non-Authoritative Information'],
    ['code' => 204, 'phrase' => '🚫 No Content',
        'description' => 'The request was successful, but there is no content to send in the response.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-204-no-content',
        'spec_title' => 'RFC9110 - 204 No Content'],
    ['code' => 205, 'phrase' => '🔄 Reset Content',
        'description' => 'The request was successful, and the user agent should reset the document view.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-205-reset-content',
        'spec_title' => 'RFC9110 - 205 Reset Content'],
    ['code' => 206, 'phrase' => '📄 Partial Content',
        'description' => 'The server is delivering only part of the resource due to a range header sent by the client.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-206-partial-content',
        'spec_title' => 'RFC9110 - 206 Partial Content'],

    // Redirection 3xx
    ['code' => 300, 'phrase' => '🔀 Multiple Choices',
        'description' => 'The request has multiple possible responses, and the user or user agent must choose one.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-300-multiple-choices',
        'spec_title' => 'RFC9110 - 300 Multiple Choices'],
    ['code' => 301, 'phrase' => '➡️ Moved Permanently',
        'description' => 'The requested resource has been permanently moved to a new location.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-301-moved-permanently',
        'spec_title' => 'RFC9110 - 301 Moved Permanently'],
    ['code' => 302, 'phrase' => '➡️ Found',
        'description' => 'The requested resource has been temporarily moved to a different location.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-302-found',
        'spec_title' => 'RFC9110 - 302 Found'],
    ['code' => 303, 'phrase' => '👀 See Other',
        'description' => 'The response to the request can be found under a different URI.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-303-see-other',
        'spec_title' => 'RFC9110 - 303 See Other'],
    ['code' => 304, 'phrase' => '🔄 Not Modified',
        'description' => 'The resource has not been modified since the last request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-304-not-modified',
        'spec_title' => 'RFC9110 - 304 Not Modified'],
    ['code' => 307, 'phrase' => '➡️ Temporary Redirect',
        'description' => 'The request should be repeated with another URI, but future requests should still use the original URI.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-307-temporary-redirect',
        'spec_title' => 'RFC9110 - 307 Temporary Redirect'],
    ['code' => 308, 'phrase' => '➡️ Permanent Redirect',
        'description' => 'The request and all future requests should be repeated using another URI.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-308-permanent-redirect',
        'spec_title' => 'RFC9110 - 308 Permanent Redirect'],

    // Client Errors 4xx
    ['code' => 400, 'phrase' => '❌ Bad Request',
        'description' => 'The server cannot process the request due to a client error.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-400-bad-request',
        'spec_title' => 'RFC9110 - 400 Bad Request'],
    ['code' => 401, 'phrase' => '🔒 Unauthorized',
        'description' => 'The client must authenticate itself to get the requested response.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-401-unauthorized',
        'spec_title' => 'RFC9110 - 401 Unauthorized'],
    ['code' => 403, 'phrase' => '🚫 Forbidden',
        'description' => 'The client does not have access rights to the content.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-403-forbidden',
        'spec_title' => 'RFC9110 - 403 Forbidden'],
    ['code' => 404, 'phrase' => '🔍 Not Found',
        'description' => 'The server cannot find the requested resource.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-404-not-found',
        'spec_title' => 'RFC9110 - 404 Not Found'],
    ['code' => 405, 'phrase' => '🚫 Method Not Allowed',
        'description' => 'The request method is not supported for the requested resource.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-405-method-not-allowed',
        'spec_title' => 'RFC9110 - 405 Method Not Allowed'],
    ['code' => 406, 'phrase' => '🚫 Not Acceptable',
        'description' => 'The server cannot produce a response matching the list of acceptable values defined in the request headers.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-406-not-acceptable',
        'spec_title' => 'RFC9110 - 406 Not Acceptable'],
    ['code' => 407, 'phrase' => '🔒 Proxy Authentication Required',
        'description' => 'The client must first authenticate itself with the proxy.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-407-proxy-authentication-required',
        'spec_title' => 'RFC9110 - 407 Proxy Authentication Required'],
    ['code' => 408, 'phrase' => '⏳ Request Timeout',
        'description' => 'The server timed out waiting for the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-408-request-timeout',
        'spec_title' => 'RFC9110 - 408 Request Timeout'],
    ['code' => 409, 'phrase' => '⚔️ Conflict',
        'description' => 'The request conflicts with the current state of the server.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-409-conflict',
        'spec_title' => 'RFC9110 - 409 Conflict'],
    ['code' => 410, 'phrase' => '💀 Gone',
        'description' => 'The requested resource is no longer available and will not be available again.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-410-gone',
        'spec_title' => 'RFC9110 - 410 Gone'],
    ['code' => 411, 'phrase' => '📏 Length Required',
        'description' => 'The request did not specify the length of its content, which is required by the requested resource.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-411-length-required',
        'spec_title' => 'RFC9110 - 411 Length Required'],
    ['code' => 412, 'phrase' => '🚫 Precondition Failed',
        'description' => 'The server does not meet one of the preconditions specified in the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-412-precondition-failed',
        'spec_title' => 'RFC9110 - 412 Precondition Failed'],
    ['code' => 413, 'phrase' => '📦 Content Too Large',
        'description' => 'The request is larger than the server is willing or able to process.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-413-content-too-large',
        'spec_title' => 'RFC9110 - 413 Content Too Large'],
    ['code' => 414, 'phrase' => '🔗 URI Too Long',
        'description' => 'The URI provided in the request is too long for the server to process.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-414-uri-too-long',
        'spec_title' => 'RFC9110 - 414 URI Too Long'],
    ['code' => 415, 'phrase' => '📄 Unsupported Media Type',
        'description' => 'The request entity has a media type that the server or resource does not support.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-415-unsupported-media-type',
        'spec_title' => 'RFC9110 - 415 Unsupported Media Type'],
    ['code' => 416, 'phrase' => '📄 Range Not Satisfiable',
        'description' => 'The client has asked for a portion of the file, but the server cannot supply that portion.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-416-range-not-satisfiable',
        'spec_title' => 'RFC9110 - 416 Range Not Satisfiable'],
    ['code' => 417, 'phrase' => '🚫 Expectation Failed',
        'description' => 'The server cannot meet the requirements of the Expect request-header field.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-417-expectation-failed',
        'spec_title' => 'RFC9110 - 417 Expectation Failed'],
    ['code' => 418, 'phrase' => '🫖 I\'m a Teapot',
        'description' => 'The server refuses the attempt to brew coffee with a teapot.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-418-im-a-teapot',
        'spec_title' => 'RFC9110 - 418 I\'m a Teapot'],
    ['code' => 421, 'phrase' => '🔄 Misdirected Request',
        'description' => 'The request was directed at a server that is not able to produce a response.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-421-misdirected-request',
        'spec_title' => 'RFC9110 - 421 Misdirected Request'],
    ['code' => 422, 'phrase' => '🚫 Unprocessable Content',
        'description' => 'The request was well-formed but was unable to be followed due to semantic errors.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content',
        'spec_title' => 'RFC9110 - 422 Unprocessable Content'],
    ['code' => 423, 'phrase' => '🔒 Locked',
        'description' => 'The resource that is being accessed is locked.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-423-locked',
        'spec_title' => 'RFC9110 - 423 Locked'],
    ['code' => 424, 'phrase' => '🚫 Failed Dependency',
        'description' => 'The request failed because it depended on another request that failed.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-424-failed-dependency',
        'spec_title' => 'RFC9110 - 424 Failed Dependency'],
    ['code' => 425, 'phrase' => '⏳ Too Early',
        'description' => 'The server is unwilling to risk processing a request that might be replayed.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-425-too-early',
        'spec_title' => 'RFC9110 - 425 Too Early'],
    ['code' => 426, 'phrase' => '⬆️ Upgrade Required',
        'description' => 'The client should switch to a different protocol.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-426-upgrade-required',
        'spec_title' => 'RFC9110 - 426 Upgrade Required'],
    ['code' => 428, 'phrase' => '🚫 Precondition Required',
        'description' => 'The server requires the request to be conditional.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-428-precondition-required',
        'spec_title' => 'RFC9110 - 428 Precondition Required'],
    ['code' => 429, 'phrase' => '⏳ Too Many Requests',
        'description' => 'The user has sent too many requests in a given amount of time.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-429-too-many-requests',
        'spec_title' => 'RFC9110 - 429 Too Many Requests'],
    ['code' => 431, 'phrase' => '📄 Request Header Fields Too Large',
        'description' => 'The server is unwilling to process the request because its header fields are too large.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-431-request-header-fields-too-large',
        'spec_title' => 'RFC9110 - 431 Request Header Fields Too Large'],
    ['code' => 451, 'phrase' => '⚖️ Unavailable For Legal Reasons',
        'description' => 'The server is denying access to the resource as a consequence of a legal demand.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-451-unavailable-for-legal-reasons',
        'spec_title' => 'RFC9110 - 451 Unavailable For Legal Reasons'],

    // Server Errors 5xx
    ['code' => 500, 'phrase' => '💥 Internal Server Error',
        'description' => 'The server encountered an unexpected condition that prevented it from fulfilling the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-500-internal-server-error',
        'spec_title' => 'RFC9110 - 500 Internal Server Error'],
    ['code' => 501, 'phrase' => '🚫 Not Implemented',
        'description' => 'The server does not support the functionality required to fulfill the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-501-not-implemented',
        'spec_title' => 'RFC9110 - 501 Not Implemented'],
    ['code' => 502, 'phrase' => '🔗 Bad Gateway',
        'description' => 'The server received an invalid response from an upstream server.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-502-bad-gateway',
        'spec_title' => 'RFC9110 - 502 Bad Gateway'],
    ['code' => 503, 'phrase' => '🚧 Service Unavailable',
        'description' => 'The server is currently unable to handle the request due to temporary overloading or maintenance.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-503-service-unavailable',
        'spec_title' => 'RFC9110 - 503 Service Unavailable'],
    ['code' => 504, 'phrase' => '⏳ Gateway Timeout',
        'description' => 'The server did not receive a timely response from an upstream server.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-504-gateway-timeout',
        'spec_title' => 'RFC9110 - 504 Gateway Timeout'],
    ['code' => 505, 'phrase' => '🚫 HTTP Version Not Supported',
        'description' => 'The server does not support the HTTP protocol version used in the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-505-http-version-not-supported',
        'spec_title' => 'RFC9110 - 505 HTTP Version Not Supported'],
    ['code' => 506, 'phrase' => '🔄 Variant Also Negotiates',
        'description' => 'The server has an internal configuration error.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-506-variant-also-negotiates',
        'spec_title' => 'RFC9110 - 506 Variant Also Negotiates'],
    ['code' => 507, 'phrase' => '💾 Insufficient Storage',
        'description' => 'The server is unable to store the representation needed to complete the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-507-insufficient-storage',
        'spec_title' => 'RFC9110 - 507 Insufficient Storage'],
    ['code' => 508, 'phrase' => '🔄 Loop Detected',
        'description' => 'The server detected an infinite loop while processing the request.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-508-loop-detected',
        'spec_title' => 'RFC9110 - 508 Loop Detected'],
    ['code' => 510, 'phrase' => '🚫 Not Extended',
        'description' => 'Further extensions to the request are required for the server to fulfill it.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-510-not-extended',
        'spec_title' => 'RFC9110 - 510 Not Extended'],
    ['code' => 511, 'phrase' => '🔒 Network Authentication Required',
        'description' => 'The client needs to authenticate to gain network access.',
        'spec_href' => 'https://www.rfc-editor.org/rfc/rfc9110.html#name-511-network-authentication-required',
        'spec_title' => 'RFC9110 - 511 Network Authentication Required'],

    // 7xx Developer-Specific Codes (Unofficial)
    ["code" => 701, "phrase" => "🎭 Meh",
        "description" => "😑 The server is bored of this request.",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 702, "phrase" => "🎮 Try Again",
        "description" => "🔄 The request failed, but you can retry.",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 710, "phrase" => "🍵 Calm Down",
        "description" => "☕ The client should relax before trying again.",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 725, "phrase" => "💩 Server on Fire",
        "description" => "🔥 The server is having a really bad day.",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 726, "phrase" => "👽 Space Overflow",
        "description" => "🚀 The server ran out of space... literally!",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 740, "phrase" => "🎭 Meme Detected",
        "description" => "😂 The request contained too many memes.",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 750, "phrase" => "🎸 Too Cool",
        "description" => "🤘 The request was rejected because it's just too awesome.",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ["code" => 777, "phrase" => "🍀 Jackpot",
        "description" => "🎰 Everything miraculously worked perfectly!",
        "spec_title" => "Unofficial",
        "spec_href" => "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status"],
    ];

function get_status_code_info($code, $http_status_codes) {
    foreach ($http_status_codes as $status) {
        if ($status['code'] == $code) {
            return $status; // Return the whole array for the matching code
        }
    }
    return ["code" => "000", "phrase" => 'Unknown Error',
        'description' => '❓ No description available.', 'spec_title' => null,
        'spec_href' => null]; // Return null if the code is not found
}