# Generated by Django 5.2.3 on 2025-06-17 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("short_name", models.CharField(max_length=60)),
                ("description", models.CharField(default="", max_length=160)),
                ("keywords", models.JSONField(default=list, max_length=160)),
                ("publisher", models.CharField(default="", max_length=60)),
                ("owner", models.CharField(default="", max_length=60)),
                ("copyright", models.CharField(default="", max_length=70)),
                ("theme_color", models.CharField(default="", max_length=7)),
                ("background_color", models.CharField(default="", max_length=7)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site setting",
                "verbose_name_plural": "Site Settings",
                "db_table": "siteSettings",
                "unique_together": {("site", "name")},
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                        verbose_name="Social Platform",
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        max_length=100, verbose_name="Profile Username/URL"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Auto-filled based on platform selection",
                        max_length=50,
                    ),
                ),
                (
                    "siteSettings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siteSettings.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
                "db_table": "socialMedia",
            },
        ),
    ]
