# Generated by Django 5.2.2 on 2025-06-09 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0005_delete_siteseo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("short_name", models.CharField(max_length=60)),
                ("description", models.CharField(default="", max_length=160)),
                ("keywords", models.JSONField(default=list, max_length=160)),
                ("publisher", models.CharField(default="", max_length=60)),
                ("owner", models.CharField(default="", max_length=60)),
                ("copyright", models.CharField(default="", max_length=70)),
                ("theme_color", models.CharField(default="", max_length=7)),
                ("background_color", models.CharField(default="", max_length=7)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site setting",
                "verbose_name_plural": "Site Settings",
                "db_table": "site_seo",
                "unique_together": {("site", "name")},
            },
        ),
    ]
