# Generated by Django 5.2.3 on 2025-06-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteSettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sitesettings",
            unique_together={("name",)},
        ),
    ]
