# Generated by Django 5.2.2 on 2025-06-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteSettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="sitesettings",
            table="siteSettings",
        ),
    ]
