# Generated by Django 5.2.2 on 2025-06-09 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteSettings", "0002_alter_sitesettings_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                        verbose_name="Social Platform",
                    ),
                ),
                (
                    "profile_name",
                    models.CharField(
                        max_length=100, verbose_name="Profile Username/URL"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Auto-filled based on platform selection",
                        max_length=50,
                    ),
                ),
                (
                    "siteSettings",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siteSettings.sitesettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
                "db_table": "socialMedia",
            },
        ),
    ]
