# Generated by Django 5.2.2 on 2025-06-09 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteSettings", "0003_socialmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="siteSettings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="siteSettings.sitesettings",
            ),
        ),
    ]
